<?xml version="1.0" encoding="utf-8"?><Database Name="SparDS" Class="SparDSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=41.21.207.231,1433;Initial Catalog=SparDS;Persist Security Info=True;User ID=sparuser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SparDSConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.listSuppliers" Method="listSuppliers" IsComposable="true">
    <Return Type="object" />
  </Function>
  <Function Name="dbo.listSuppliers_new" Method="listSuppliers_new">
    <ElementType Name="listSuppliers_newResult">
      <Column Name="SPcName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryEan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecondaryEan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SPcVatNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.listSuppliersLinkedToDC" Method="listSuppliersLinkedToDC">
    <Parameter Name="DCId" Parameter="dCId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExcludeInactiveSuppliers" Parameter="excludeInactiveSuppliers" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ReportOption" Parameter="reportOption" Type="System.String" DbType="VarChar(55)" />
    <ElementType Name="listSuppliersLinkedToDCResult">
      <Column Name="[DC Vendor Name]" Member="DC_Vendor_Name" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="[DC Vendor Code]" Member="DC_Vendor_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[DC Vendor Status]" Member="DC_Vendor_Status" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="[DC Vendor Vat Number]" Member="DC_Vendor_Vat_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Primary EAN]" Member="Primary_EAN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Secondary EAN]" Member="Secondary_EAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Vat number on Gateway]" Member="Vat_number_on_Gateway" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Supplier Name on Gateway]" Member="Supplier_Name_on_Gateway" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OrderEmailAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EDIGroupCode" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EDIGroupCodeEan" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SupplierOrderMethod" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="StoreOrderMethod" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="[Supplier Category]" Member="Supplier_Category" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="[Capture Claim for Supplier Indicator]" Member="Capture_Claim_for_Supplier_Indicator" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="[Supplier Email Address]" Member="Supplier_Email_Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>