<!--
var tocTab = new Array();var ir=0;
tocTab[ir++] = new Array ('0', 'Menu', '');
tocTab[ir++] = new Array ('1', 'Distribution Centre', 'https://spar.gatewayec.co.za/portal/track/frmcontent.asp?id=DC');
tocTab[ir++] = new Array ('1.1', 'Reports', 'https://spar.gatewayec.co.za/portal/track/frmcontent.asp?id=DCReport');
tocTab[ir++] = new Array ('1.1.1', 'Statistical Data', 'https://spar.gatewayec.co.za/portal/report/stats/default.asp');
tocTab[ir++] = new Array ('1.1.2', 'Supplier Compliance per Buyer', 'https://spar.gatewayec.co.za/portal/report/supplier/default.asp');
tocTab[ir++] = new Array ('1.2', 'Administration', 'https://spar.gatewayec.co.za/portal/track/frmcontent.asp?id=DCAdmin');
tocTab[ir++] = new Array ('1.2.1', 'Buyers', '');
tocTab[ir++] = new Array ('1.2.1.1', 'List Buyers', 'https://spar.gatewayec.co.za/portal/admin/dc/buyer');
tocTab[ir++] = new Array ('1.2.1.2', 'Add new Buyer', 'https://spar.gatewayec.co.za/portal/admin/dc/buyer/item.asp');
tocTab[ir++] = new Array ('1.2.1.3', 'Track a Buyer', 'https://spar.gatewayec.co.za/portal/admin/dc/buyer/search/default.asp');
tocTab[ir++] = new Array ('1.2.2', 'Suppliers', '');
tocTab[ir++] = new Array ('1.2.2.1', 'List Suppliers', 'https://spar.gatewayec.co.za/portal/admin/dc/supplier');
tocTab[ir++] = new Array ('1.2.2.2', 'Add new Supplier', 'https://spar.gatewayec.co.za/portal/admin/dc/supplier/item.asp');
tocTab[ir++] = new Array ('1.2.3', 'Lookup', 'https://spar.gatewayec.co.za/portal/admin/dc/password/');
tocTab[ir++] = new Array ('1.2.4', 'Generate Mail', 'https://spar.gatewayec.co.za/portal/admin/dc/mail/');
tocTab[ir++] = new Array ('1.2.5', 'Order Search', 'https://spar.gatewayec.co.za/portal/OrderSearch/');
tocTab[ir++] = new Array ('2', 'Drop Shipment', 'https://spar.gatewayec.co.za/portal/track/frmcontent.asp?id=DS');
tocTab[ir++] = new Array ('2.1', 'Reports', 'https://spar.gatewayec.co.za/portal/track/frmcontent.asp?id=DSReport');
tocTab[ir++] = new Array ('2.2', 'Administration', 'https://spar.gatewayec.co.za/portal/track/frmcontent.asp?id=DSAdmin');
tocTab[ir++] = new Array ('2.2.1', 'Stores', '');
tocTab[ir++] = new Array ('2.2.1.1', 'List Stores', 'https://spar.gatewayec.co.za/portal/admin/ds/store/');
tocTab[ir++] = new Array ('2.2.1.2', 'Add new Store', 'https://spar.gatewayec.co.za/portal/admin/ds/store/item.asp');
tocTab[ir++] = new Array ('2.2.2', 'Suppliers', '');
tocTab[ir++] = new Array ('2.2.2.1', 'List Suppliers', 'https://spar.gatewayec.co.za/portal/admin/ds/supplier');
tocTab[ir++] = new Array ('2.2.2.2', 'Add new Supplier', 'https://spar.gatewayec.co.za/portal/admin/ds/supplier/item.asp');
tocTab[ir++] = new Array ('2.2.2.3', 'Create new Supplier', 'https://spar.gatewayec.co.za/portal/admin/ds/supplier/CreateSupplier.asp');
tocTab[ir++] = new Array ('2.2.3', 'Search', 'https://spar.gatewayec.co.za/portal/admin/ds/search/default.asp');
tocTab[ir++] = new Array ('2.2.4', 'Lookup', 'https://spar.gatewayec.co.za/portal/admin/ds/password/default.asp');
tocTab[ir++] = new Array ('4', 'System Monitor', 'https://spar.gatewayec.co.za/portal/track/frmcontent.asp?id=Monitor');
tocTab[ir++] = new Array ('4.1', '23 October 2023', 'https://spar.gatewayec.co.za/portal/monitor/default.asp?id=23 October 2023');
tocTab[ir++] = new Array ('4.2', '22 October 2023', 'https://spar.gatewayec.co.za/portal/monitor/default.asp?id=22 October 2023');
tocTab[ir++] = new Array ('4.3', '21 October 2023', 'https://spar.gatewayec.co.za/portal/monitor/default.asp?id=21 October 2023');
tocTab[ir++] = new Array ('4.4', '20 October 2023', 'https://spar.gatewayec.co.za/portal/monitor/default.asp?id=20 October 2023');
tocTab[ir++] = new Array ('4.5', '19 October 2023', 'https://spar.gatewayec.co.za/portal/monitor/default.asp?id=19 October 2023');
tocTab[ir++] = new Array ('4.6', '18 October 2023', 'https://spar.gatewayec.co.za/portal/monitor/default.asp?id=18 October 2023');
tocTab[ir++] = new Array ('4.7', '17 October 2023', 'https://spar.gatewayec.co.za/portal/monitor/default.asp?id=17 October 2023');
tocTab[ir++] = new Array ('5', 'Logout', 'https://spar.gatewayec.co.za/portal/logout/default.asp');
var nCols = 4;
//-->
