<!--#include file="ExecuteProcedure.asp"-->
<%
	' This include file will display the constants for the CMS
	Const adCmdStoredProc = &H0004
	const const_db_ConnectionString = "Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=SparDS;Data Source=192.168.101.36,1433"
	const const_db_SparClaimsConnectionString = "Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=False;Initial Catalog=SparClaims;Data Source=192.168.101.36,1433"
	const const_db_ReportConnection = "Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=True;Initial Catalog=SparDS;Data Source=192.168.101.36,1433"
	Const const_app_ApplicationRoot = "https://spar.gatewayec.co.za/dropship"
	Const const_app_DocumentRoot = "https://spar.gatewayec.co.za/"
	Const const_app_Moniker = "SPAR"
	Const const_app_UploadPath = "C:\InetPub\wwwroot\sparv2\dropship\images"
	Const const_app_DownloadPath = "https://spar.gatewayec.co.za/dropship/images"
	Const const_app_SupplierPath = "https://spar.gatewayec.co.za/dropship/SparIn/Supplier/"
	Const const_app_BuyerPath = "https://spar.gatewayec.co.za/dropship/SparIn/Buyer/"
	Const const_app_XMLDownloadPath = "https://spar.gatewayec.co.za/dropship/sparIn"
	Const const_app_XMLDownloadOutPath = "https://spar.gatewayec.co.za/dropship/tracktrace/supplier/tabs/"
	'Const const_app_VirtualPath = "C:\InetPub\wwwroot\sparv2\dropship\SparIn"
	Const const_app_TabFile = "C:\spar\tabfile\"
	Const const_app_TrackPath = "C:\InetPub\wwwroot\sparv2\dropship\tracktrace\"
	'Const const_app_XMLDownloadTabPath = "C:\InetPub\wwwroot\sparv2\dropship\tracktrace\supplier\tabs\"
	'Const const_app_LocalDrive = "C:\Saved Files\"
	Const const_app_OverwriteMode1 = 0
	Const const_app_OverwriteMode2 = 1
	Const const_app_OverwriteMode3 = 2
	Const const_app_ValidExtentions = "zip,txt,jpg,gif"
	Const const_appMaxUploadSize = 0		' Set to default 0 or else set the value im MB e.g 2048 = 2MB
	Const const_app_MailObject = "CDONTS.NewMail"
	Const const_app_XMLObject = "MSXML2.DomDocument"
	Const const_app_SparInPath = "\\ecintprd\ec-clients\spar\SparIn\"
	Const const_app_SparOutPath = "\\ecintprd\ec-clients\spar\SparOut\"
	Const const_app_SparArcPath = "\\ecintprd\ec-clients\spar\SparOrders\"
	Const const_app_ReconXMLFixedPath = "C:\spar\dropship\Recon_XML\"
	Const const_app_IncludePath = "C:\InetPub\wwwroot\sparv2\dropship\includes\"
	'Const const_app_CreditNotePath = "C:\InetPub\wwwroot\sparv2\dropship\track\supplier\creditnote\mq\"
	'Const const_app_MQPath = "C:\InetPub\wwwroot\sparv2\dropship\storeval\mq\"
	Const const_app_WebReportFixedPath = "C:\spar\dropship\stats\billing\"
	Const const_app_uploaddir = "C:\spar\dropship\schedule\upload\"
	Const const_app_schedOutDir = "\\ecintprd\ec-clients\spar\SparDS\schedules\out\"
	Const const_app_schedDelayDir = "\\ecintprd\ec-clients\spar\SparDS\schedules\delay\"
	Const const_app_schedDownloadDir = "\\ecintprd\ec-clients\spar\SparDS\schedules\download\"
	Const Const_ElectronicRemittance_TempSave = "C:\spar\dropship\remittanceadvices\tempsave\"
	Const const_app_SqlReportsPath = "C:\InetPub\wwwroot\sparv2\dropship\sqlreports\"
	Const Const_App_New = "https://ecweb.vbecom.co.za/sparclaims/"
	'Const BackupServerShare = "\\192.168.101.53\p"
	Const ServerShare = "\\192.168.101.54\f"
	'Const ServerShare = "\\192.168.101.53\p"
	'Const BackupServerShare = "\\192.168.101.54\f"
	Const AwsServerShare = "\\192.168.100.65\vb-ecs-ecommerce-spar"
	Const Const_App_ClaimsUploadDir = "q:\spar\dropship\claims\upload\"
	Const Const_App_ClaimsUploadDirBackup = "x:\spar\dropship\claims\upload\"
	Const Const_App_AwsClaimsUploadDir = "y:\spar\dropship\claims\upload\"
	'Const Const_App_ClaimsUploadDirWhack = "\\192.168.101.53\p\"
	Const Const_App_ClaimsUploadDirBackupWhack = "\\192.168.101.54\f\"
	'Const Const_App_ClaimsUploadDirAwsWhack = "\\192.168.101.54\f\"
	Const Const_Invoice_Download = "C:\spar\dropship\invoice\downloads\"
	Const Const_ClaimsBatchUpload = "C:\spar\dropship\claims\BatchStatusChangeUploads\"
	Const Const_StoreList_TempSave = "C:\spar\dropship\storelist\"
	
%>