<!--
var tocTab = new Array();var ir=0;
tocTab[ir++] = new Array ('0', 'Date Menu', '');
tocTab[ir++] = new Array ('1', '23 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=23 Oct 2023');
tocTab[ir++] = new Array ('2', '22 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=22 Oct 2023');
tocTab[ir++] = new Array ('3', '21 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=21 Oct 2023');
tocTab[ir++] = new Array ('4', '20 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=20 Oct 2023');
tocTab[ir++] = new Array ('5', '19 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=19 Oct 2023');
tocTab[ir++] = new Array ('6', '18 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=18 Oct 2023');
tocTab[ir++] = new Array ('7', '17 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=17 Oct 2023');
tocTab[ir++] = new Array ('8', '16 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=16 Oct 2023');
tocTab[ir++] = new Array ('9', 'Before 15 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=15 Oct 2023');
tocTab[ir++] = new Array ('9.1', '14 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=14 Oct 2023');
tocTab[ir++] = new Array ('9.2', '13 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=13 Oct 2023');
tocTab[ir++] = new Array ('9.3', '12 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=12 Oct 2023');
tocTab[ir++] = new Array ('9.4', '11 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=11 Oct 2023');
tocTab[ir++] = new Array ('9.5', '10 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=10 Oct 2023');
tocTab[ir++] = new Array ('9.6', '9 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=9 Oct 2023');
tocTab[ir++] = new Array ('9.7', '8 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=8 Oct 2023');
tocTab[ir++] = new Array ('9.8', '7 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=7 Oct 2023');
tocTab[ir++] = new Array ('9.9', '6 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=6 Oct 2023');
tocTab[ir++] = new Array ('9.10', '5 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=5 Oct 2023');
tocTab[ir++] = new Array ('9.11', '4 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=4 Oct 2023');
tocTab[ir++] = new Array ('9.12', '3 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=3 Oct 2023');
tocTab[ir++] = new Array ('9.13', '2 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=2 Oct 2023');
tocTab[ir++] = new Array ('9.14', '1 Oct 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=1 Oct 2023');
tocTab[ir++] = new Array ('9.15', '30 Sep 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=30 Sep 2023');
tocTab[ir++] = new Array ('9.16', '29 Sep 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=29 Sep 2023');
tocTab[ir++] = new Array ('9.17', '28 Sep 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=28 Sep 2023');
tocTab[ir++] = new Array ('9.18', '27 Sep 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=27 Sep 2023');
tocTab[ir++] = new Array ('9.19', '26 Sep 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=26 Sep 2023');
tocTab[ir++] = new Array ('9.20', '25 Sep 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=25 Sep 2023');
tocTab[ir++] = new Array ('9.21', '24 Sep 2023', 'https://spar.gatewayec.co.za/dropship/track/supplier/frmcontent.asp?id=24 Sep 2023');
var nCols = 4;
//-->
