var tocTab = new Array();var ir=0;
tocTab[ir++] = new Array ('0', '  Date Menu  ', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=20 October 2023');
tocTab[ir++] = new Array ('1', '20 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=20 October 2023');
tocTab[ir++] = new Array ('2', '19 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=19 October 2023');
tocTab[ir++] = new Array ('3', '18 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=18 October 2023');
tocTab[ir++] = new Array ('4', '17 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=17 October 2023');
tocTab[ir++] = new Array ('5', '16 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=16 October 2023');
tocTab[ir++] = new Array ('6', '15 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=15 October 2023');
tocTab[ir++] = new Array ('7', '14 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=14 October 2023');
tocTab[ir++] = new Array ('8', '13 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=13 October 2023');
tocTab[ir++] = new Array ('9', 'Before 12 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=12 October 2023');
tocTab[ir++] = new Array ('9.1', '11 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=11 October 2023');
tocTab[ir++] = new Array ('9.2', '10 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=10 October 2023');
tocTab[ir++] = new Array ('9.3', '9 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=9 October 2023');
tocTab[ir++] = new Array ('9.4', '8 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=8 October 2023');
tocTab[ir++] = new Array ('9.5', '7 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=7 October 2023');
tocTab[ir++] = new Array ('9.6', '6 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=6 October 2023');
tocTab[ir++] = new Array ('9.7', '5 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=5 October 2023');
tocTab[ir++] = new Array ('9.8', '4 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=4 October 2023');
tocTab[ir++] = new Array ('9.9', '3 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=3 October 2023');
tocTab[ir++] = new Array ('9.10', '2 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=2 October 2023');
tocTab[ir++] = new Array ('9.11', '1 October 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=1 October 2023');
tocTab[ir++] = new Array ('9.12', '30 September 2023', 'https://spar.gatewayec.co.za//tracktrace/buyer/frmcontent.asp?id=30 September 2023');
var nCols = 4;
