<!--
var tocTab = new Array();var ir=0;
tocTab[ir++] = new Array ('0', 'Date Menu', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=23 October 2023');
tocTab[ir++] = new Array ('1', '23 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=23 October 2023');
tocTab[ir++] = new Array ('2', '22 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=22 October 2023');
tocTab[ir++] = new Array ('3', '21 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=21 October 2023');
tocTab[ir++] = new Array ('4', '20 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=20 October 2023');
tocTab[ir++] = new Array ('5', '19 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=19 October 2023');
tocTab[ir++] = new Array ('6', '18 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=18 October 2023');
tocTab[ir++] = new Array ('7', '17 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=17 October 2023');
tocTab[ir++] = new Array ('8', '16 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=16 October 2023');
tocTab[ir++] = new Array ('9', 'Before 15 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=15 October 2023');
tocTab[ir++] = new Array ('9.1', '14 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=14 October 2023');
tocTab[ir++] = new Array ('9.2', '13 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=13 October 2023');
tocTab[ir++] = new Array ('9.3', '12 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=12 October 2023');
tocTab[ir++] = new Array ('9.4', '11 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=11 October 2023');
tocTab[ir++] = new Array ('9.5', '10 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=10 October 2023');
tocTab[ir++] = new Array ('9.6', '9 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=9 October 2023');
tocTab[ir++] = new Array ('9.7', '8 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=8 October 2023');
tocTab[ir++] = new Array ('9.8', '7 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=7 October 2023');
tocTab[ir++] = new Array ('9.9', '6 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=6 October 2023');
tocTab[ir++] = new Array ('9.10', '5 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=5 October 2023');
tocTab[ir++] = new Array ('9.11', '4 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=4 October 2023');
tocTab[ir++] = new Array ('9.12', '3 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=3 October 2023');
tocTab[ir++] = new Array ('9.13', '2 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=2 October 2023');
tocTab[ir++] = new Array ('9.14', '1 October 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=1 October 2023');
tocTab[ir++] = new Array ('9.15', '30 September 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=30 September 2023');
tocTab[ir++] = new Array ('9.16', '29 September 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=29 September 2023');
tocTab[ir++] = new Array ('9.17', '28 September 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=28 September 2023');
tocTab[ir++] = new Array ('9.18', '27 September 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=27 September 2023');
tocTab[ir++] = new Array ('9.19', '26 September 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=26 September 2023');
tocTab[ir++] = new Array ('9.20', '25 September 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=25 September 2023');
tocTab[ir++] = new Array ('9.21', '24 September 2023', 'https://spar.gatewayec.co.za//tracktrace/supplier/frmcontent.asp?id=24 September 2023');
var nCols = 4;
//-->
